spring.application.name=trabalho-01-cfm
spring.data.mongodb.uri=${MONGODB_URI:mongodb://localhost:27017/trabalho01_cfm?serverSelectionTimeoutMS=5000}
spring.datasource.url=jdbc:h2:mem:batch_metadata;DB_CLOSE_DELAY=-1
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.batch.jdbc.initialize-schema=always
spring.batch.job.enabled=false
