spring.application.name=trabalho-01-cfm
spring.data.mongodb.uri=${MONGODB_URI:mongodb://localhost:27017/trabalho01_cfm}
spring.datasource.url=jdbc:h2:file:./batch-metadata;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.batch.jdbc.initialize-schema=always
spring.batch.job.enabled=false
logging.level.root=INFO
